name: Build & Deploy Spring App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file social/pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -f /Oauth2-Springboot3-Social-Login/social/pom.xml -B package