name: Build & Deploy Spring App
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: List files in working directory
        run: ls -la

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: |
          pwd
          mvn -B -X test --file social/pom.xml

      - name: Clean the application
        run: mvn clean

      - name: Build the application
        run: |
          pwd
          mvn -B -X package --file social/pom.xml